window.addEventListener("load", function (sq) {
    const square = document.getElementsByClassName("square")[0]; // THIS ZERO MEANS STARTING FROM ZERO LIKE WE USED IN SLIDER (INDEX = 0)
    window.addEventListener("scroll", function () {
        const height = document.body.clientHeight - window.innerHeight;
        const width = document.body.clientWidth;// WE DIDN'T USED (- INNERWIDTH ) BECAUSE WE HAVEN'T ANY HORIZONTAL SCROLL 
        const scroll = window.scrollY;// BECAUSE WE WANTED ONLY VERTICAL SCROLL THEREFORE (SCROLLY)
        const ratio = (scroll / height); // SCROLL / HEIGHT BECAUSE WE JUST WANTED RESULT OF HEIGHT ACCORDING TO THE RESPECTIVE SCROLL
        const dy = ratio * window.innerHeight; // RATIO WHICH IS EQUAL TO (SCROLL/HEIGHT ) AS WE MENTIONED AND WE MULTIPLY BY INNERHEIGHT BECAUSE WE USED CLIENTHEIGHT - WINDOW.INNERHEIGHT
        const dx = ratio * width;
        console.log({scroll, dx, ratio});
        square.style.top = `${dy}px`; // $ SIGN MEANS ALL OF THEM
        square.style.right = ` ${dx}px`;
        square.style.marginRight = `100px`; // REMEBER WE DONT USED (DESH) IN JAVASCRIPT INSTEAD WE USED THE FIRST LETTER AFTER DESH AS TO BE CAPITAL AS WE USE THERE
    }); 
}, false);

// CLIENTHEIGHT MEANS THE TOTAL HEIGHT AVAILABLE IN OURS WEB-PAGE BODY IT JUST THE MATTER OF CONTENT WE USED IN THE BODY THE HEIGHT WILL INCREASES ACCORDING TO OURS CONTENT IN BODY FOR INSTANCE IN THIS WEB-SITE (DEV-JAVASCRIPT-WEBPAGE) THE TOTAL CONTENT CLIENT HEIGHT IS ABOUT 3856PX (AND YOUUU) CAN CONFIRM IT BY GOING TO THE  CONSOLE THEN SCROLL TO BOTTOM THEN YOU CAN CHECK THAT 3856PX IS AVAILABLE WE SCROLLED DOWN 3403.5 PX MEANS RESIDUE OR INNERHEIGHT AVAILABLE IS 452PX IT CAN BE DIFFERENT IF WE INCREASES OR DECREASE THE CONSOLE HEIGHTS IT SELF


// INNERHEIGHT IS BASICALLY THE HEIGHT VISIBLE IT CAN BE 500PX IF VISIBLE IN FULL PAGE AND IT CAN 300PX IF WE OPEN CONSOLE IT JUST DEPENDS UPON HOW MUCH CONTENT IS (VISIBLE)